import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.scss";
import { ThemeProvider } from "react-bootstrap";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeProvider
          breakpoints={["xl", "md"]}
          minBreakpoint="xxs"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
